new Vue({
    el:"#root",
    data:{
        datas:[
            {
                id:1,
                title:"AAA",
            },
            {
                id:2,
                title:"BBBB",
            },
            {
                id:3,
                title:"CCCCC",
            },
        ],
        title:"",
        state:false
    },
    methods:{
        aa(){
            this.state=true;
        },
        bb(val){
            this.title=val;
            this.state=false;
        }
    }
})
